package entity;

import java.util.Date;

public class Check {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.checkMan
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String checkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.standardValue
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String standardvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.checkValue
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String checkvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.checkDate
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Date checkdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.advice
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String advice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.reason
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.checkNo
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String checkno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.id
     *
     * @return the value of check.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.id
     *
     * @param id the value for check.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.checkMan
     *
     * @return the value of check.checkMan
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getCheckman() {
        return checkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.checkMan
     *
     * @param checkman the value for check.checkMan
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setCheckman(String checkman) {
        this.checkman = checkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.standardValue
     *
     * @return the value of check.standardValue
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getStandardvalue() {
        return standardvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.standardValue
     *
     * @param standardvalue the value for check.standardValue
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setStandardvalue(String standardvalue) {
        this.standardvalue = standardvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.checkValue
     *
     * @return the value of check.checkValue
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getCheckvalue() {
        return checkvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.checkValue
     *
     * @param checkvalue the value for check.checkValue
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setCheckvalue(String checkvalue) {
        this.checkvalue = checkvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.checkDate
     *
     * @return the value of check.checkDate
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Date getCheckdate() {
        return checkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.checkDate
     *
     * @param checkdate the value for check.checkDate
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setCheckdate(Date checkdate) {
        this.checkdate = checkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.advice
     *
     * @return the value of check.advice
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getAdvice() {
        return advice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.advice
     *
     * @param advice the value for check.advice
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setAdvice(String advice) {
        this.advice = advice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.reason
     *
     * @return the value of check.reason
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.reason
     *
     * @param reason the value for check.reason
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.checkNo
     *
     * @return the value of check.checkNo
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getCheckno() {
        return checkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.checkNo
     *
     * @param checkno the value for check.checkNo
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setCheckno(String checkno) {
        this.checkno = checkno;
    }
}