package entity;

public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.companyName
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String companyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.phone
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.email
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.linkman
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String linkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.address
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.id
     *
     * @return the value of client.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.id
     *
     * @param id the value for client.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.companyName
     *
     * @return the value of client.companyName
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.companyName
     *
     * @param companyname the value for client.companyName
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.phone
     *
     * @return the value of client.phone
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.phone
     *
     * @param phone the value for client.phone
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.email
     *
     * @return the value of client.email
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.email
     *
     * @param email the value for client.email
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.linkman
     *
     * @return the value of client.linkman
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.linkman
     *
     * @param linkman the value for client.linkman
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.address
     *
     * @return the value of client.address
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.address
     *
     * @param address the value for client.address
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }
}