package entity;

public class Material {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.vaccineId
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Integer vaccineid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.material
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String material;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.id
     *
     * @return the value of material.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.id
     *
     * @param id the value for material.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.vaccineId
     *
     * @return the value of material.vaccineId
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Integer getVaccineid() {
        return vaccineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.vaccineId
     *
     * @param vaccineid the value for material.vaccineId
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setVaccineid(Integer vaccineid) {
        this.vaccineid = vaccineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.material
     *
     * @return the value of material.material
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.material
     *
     * @param material the value for material.material
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setMaterial(String material) {
        this.material = material;
    }
}