package entity;

import java.util.Date;

public class Orderplan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderplan.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderplan.checkState
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String checkstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderplan.produceTools
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String producetools;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderplan.readyWork
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String readywork;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderplan.planTime
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Date plantime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderplan.orderId
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Integer orderid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderplan.id
     *
     * @return the value of orderplan.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderplan.id
     *
     * @param id the value for orderplan.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderplan.checkState
     *
     * @return the value of orderplan.checkState
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getCheckstate() {
        return checkstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderplan.checkState
     *
     * @param checkstate the value for orderplan.checkState
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setCheckstate(String checkstate) {
        this.checkstate = checkstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderplan.produceTools
     *
     * @return the value of orderplan.produceTools
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getProducetools() {
        return producetools;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderplan.produceTools
     *
     * @param producetools the value for orderplan.produceTools
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setProducetools(String producetools) {
        this.producetools = producetools;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderplan.readyWork
     *
     * @return the value of orderplan.readyWork
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getReadywork() {
        return readywork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderplan.readyWork
     *
     * @param readywork the value for orderplan.readyWork
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setReadywork(String readywork) {
        this.readywork = readywork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderplan.planTime
     *
     * @return the value of orderplan.planTime
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Date getPlantime() {
        return plantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderplan.planTime
     *
     * @param plantime the value for orderplan.planTime
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setPlantime(Date plantime) {
        this.plantime = plantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderplan.orderId
     *
     * @return the value of orderplan.orderId
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderplan.orderId
     *
     * @param orderid the value for orderplan.orderId
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }
}