package entity;

import java.util.Date;

public class Produce {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column produce.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column produce.orderId
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column produce.produceNo
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String produceno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column produce.machineNo
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String machineno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column produce.beginTime
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Date begintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column produce.endTime
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column produce.normal
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Boolean normal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column produce.id
     *
     * @return the value of produce.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column produce.id
     *
     * @param id the value for produce.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column produce.orderId
     *
     * @return the value of produce.orderId
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column produce.orderId
     *
     * @param orderid the value for produce.orderId
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column produce.produceNo
     *
     * @return the value of produce.produceNo
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getProduceno() {
        return produceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column produce.produceNo
     *
     * @param produceno the value for produce.produceNo
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setProduceno(String produceno) {
        this.produceno = produceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column produce.machineNo
     *
     * @return the value of produce.machineNo
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getMachineno() {
        return machineno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column produce.machineNo
     *
     * @param machineno the value for produce.machineNo
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setMachineno(String machineno) {
        this.machineno = machineno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column produce.beginTime
     *
     * @return the value of produce.beginTime
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column produce.beginTime
     *
     * @param begintime the value for produce.beginTime
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column produce.endTime
     *
     * @return the value of produce.endTime
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column produce.endTime
     *
     * @param endtime the value for produce.endTime
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column produce.normal
     *
     * @return the value of produce.normal
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Boolean getNormal() {
        return normal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column produce.normal
     *
     * @param normal the value for produce.normal
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setNormal(Boolean normal) {
        this.normal = normal;
    }
}