package entity;

import java.util.Date;

public class Vaccinein {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccinein.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccinein.clientId
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Integer clientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccinein.vaccineId
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Integer vaccineid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccinein.produceNo
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String produceno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccinein.inDate
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Date indate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccinein.inNumber
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Integer innumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccinein.outDate
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Date outdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccinein.id
     *
     * @return the value of vaccinein.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccinein.id
     *
     * @param id the value for vaccinein.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccinein.clientId
     *
     * @return the value of vaccinein.clientId
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Integer getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccinein.clientId
     *
     * @param clientid the value for vaccinein.clientId
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setClientid(Integer clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccinein.vaccineId
     *
     * @return the value of vaccinein.vaccineId
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Integer getVaccineid() {
        return vaccineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccinein.vaccineId
     *
     * @param vaccineid the value for vaccinein.vaccineId
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setVaccineid(Integer vaccineid) {
        this.vaccineid = vaccineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccinein.produceNo
     *
     * @return the value of vaccinein.produceNo
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getProduceno() {
        return produceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccinein.produceNo
     *
     * @param produceno the value for vaccinein.produceNo
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setProduceno(String produceno) {
        this.produceno = produceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccinein.inDate
     *
     * @return the value of vaccinein.inDate
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Date getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccinein.inDate
     *
     * @param indate the value for vaccinein.inDate
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setIndate(Date indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccinein.inNumber
     *
     * @return the value of vaccinein.inNumber
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Integer getInnumber() {
        return innumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccinein.inNumber
     *
     * @param innumber the value for vaccinein.inNumber
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setInnumber(Integer innumber) {
        this.innumber = innumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccinein.outDate
     *
     * @return the value of vaccinein.outDate
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Date getOutdate() {
        return outdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccinein.outDate
     *
     * @param outdate the value for vaccinein.outDate
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setOutdate(Date outdate) {
        this.outdate = outdate;
    }
}