package entity;

public class Vaccine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine.vaccineName
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String vaccinename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine.vaccineType
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String vaccinetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine.vaccineProperty
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String vaccineproperty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine.vaccineForm
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String vaccineform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine.vaccineStandard
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private String vaccinestandard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine.advancePrice
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    private Integer advanceprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine.id
     *
     * @return the value of vaccine.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine.id
     *
     * @param id the value for vaccine.id
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine.vaccineName
     *
     * @return the value of vaccine.vaccineName
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getVaccinename() {
        return vaccinename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine.vaccineName
     *
     * @param vaccinename the value for vaccine.vaccineName
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setVaccinename(String vaccinename) {
        this.vaccinename = vaccinename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine.vaccineType
     *
     * @return the value of vaccine.vaccineType
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getVaccinetype() {
        return vaccinetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine.vaccineType
     *
     * @param vaccinetype the value for vaccine.vaccineType
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setVaccinetype(String vaccinetype) {
        this.vaccinetype = vaccinetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine.vaccineProperty
     *
     * @return the value of vaccine.vaccineProperty
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getVaccineproperty() {
        return vaccineproperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine.vaccineProperty
     *
     * @param vaccineproperty the value for vaccine.vaccineProperty
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setVaccineproperty(String vaccineproperty) {
        this.vaccineproperty = vaccineproperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine.vaccineForm
     *
     * @return the value of vaccine.vaccineForm
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getVaccineform() {
        return vaccineform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine.vaccineForm
     *
     * @param vaccineform the value for vaccine.vaccineForm
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setVaccineform(String vaccineform) {
        this.vaccineform = vaccineform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine.vaccineStandard
     *
     * @return the value of vaccine.vaccineStandard
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public String getVaccinestandard() {
        return vaccinestandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine.vaccineStandard
     *
     * @param vaccinestandard the value for vaccine.vaccineStandard
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setVaccinestandard(String vaccinestandard) {
        this.vaccinestandard = vaccinestandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine.advancePrice
     *
     * @return the value of vaccine.advancePrice
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public Integer getAdvanceprice() {
        return advanceprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine.advancePrice
     *
     * @param advanceprice the value for vaccine.advancePrice
     *
     * @mbg.generated Sun Mar 10 08:24:52 CST 2019
     */
    public void setAdvanceprice(Integer advanceprice) {
        this.advanceprice = advanceprice;
    }
}